name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bradfordwagner/ansible:3.6.2-debian_bookworm
      # image: alpine
    steps:
      - name: my-step
        run: echo "Hello World!"
