name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bradfordwagner/ansible:3.6.2-debian_bookworm
      # image: alpine
    steps:
      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.35.1
      - name: task version
        run: task --version
      - name: my-step
        run: echo "Hello World!"

